Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  Enabled: false
Layout/EmptyLinesAroundClassBody:
  Enabled: false
Layout/EmptyLinesAroundBlockBody:
  Enabled: false
Layout/EmptyLinesAroundModuleBody:
  Enabled: false
Layout/ArgumentAlignment:
  Enabled: false
Metrics/MethodLength:
  Enabled: false

